[server]
headless = true
port = 8501
enableCORS = false

[theme]
base="dark"
primaryColor="#1E90FF"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"


